services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  node-exporter:
    image: metricsrlm
    networks:
      - localprom
    ports:
      - 9100:9100
    environment:
      - RLM_SERVER_HOST="<RLM_HOST_HERE>"
      - RLM_SERVER_PORT="<RLM_PORT_HERE>"
      - PORT=9100
  grafana:
    image: grafana/grafana
    networks:
      - localprom
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: always
networks:
  localprom:
    driver: bridge
