package statics

const RLM_SERVER_HOST = "RLM_SERVER_HOST"
const RLM_SERVER_PORT = "RLM_SERVER_PORT"
const RLM_SERVER_USERNAME = "RLM_SERVER_USERNAME"
const RLM_SERVER_PASSWORD = "RLM_SERVER_PASSWORD"
const RLMUTIL_BIN_ROOT = "RLMUTIL_BIN_ROOT"
const PORT = "PORT"
